Repository HackYourFuture-CPH/web-dev-rooms, pull requests merged in 2020-12, with the labels that each got.

#55 Created a Storybook Avatar for the 3 Roles, #12
  src/client/assets/images/admin.png
  src/client/assets/images/mentor.png
  src/client/assets/images/student.png
  src/client/components/Avatar/Avatar.css
  src/client/components/Avatar/Avatar.js
  src/client/components/Avatar/Avatar.stories.js
Labels: storybook

#93 correction-study group logo
  src/client/components/StudyGroupLogo/StudyGroupLogo.styles.css
Labels: frontend

#53 Added Title and text card issue #15
  src/client/components/Card/Card.js
  src/client/components/Card/Card.stories.js
  src/client/components/Card/Card.styles.css
Labels: storybook

#98 New PR for migration tables topics, modules and feedback arrived
  src/server/migrations/20200510015322_create_modules_schema.js
  src/server/migrations/20201122154020_create_modules_table.js
  src/server/migrations/20201125222030_create_topics_tables.js
  src/server/migrations/20201130170700_create_feedback_table.js
  src/server/seeds/development/modules.js
Labels: databases

#95 Modification to PR #89 card with event or study group
  src/client/components/Button/Button.js
  src/client/components/Button/Button.stories.js
  src/client/components/Button/Button.styles.css
  src/client/components/CardWithEventsOrStudyGroups/CardWithEventsOrStudyGroups.js
  src/client/components/CardWithEventsOrStudyGroups/CardWithEventsOrStudyGroups.stories.js
  src/client/components/CardWithEventsOrStudyGroups/CardWithEventsOrStudyGroups.styles.css
  src/client/components/EventCardText/EventCardText.js
  src/client/components/EventCardText/EventCardText.stories.js
  src/client/components/EventCardText/EventCardText.styles.css
Labels: frontend

#106 Create migrations for Events, Event_users, Event_students, Event_ment…
  src/server/migrations/20201201203219_events_users.js
  src/server/migrations/20201201203259_events.js
  src/server/migrations/20201201203318_events_students.js
  src/server/migrations/20201201203342_events_mentors.js
Labels: databases

#99 login page
  __mocks__/fileMock.js
  src/client/components/HyfBigLogo/HyfBigLogo.js
  src/client/components/HyfBigLogo/HyfBigLogo.style.css
  src/client/components/HyfBigLogo/hyfLogo.png
  src/client/components/SignInButton/Button.css
  src/client/containers/LoginPage/LoginPage.component.js
Labels: frontend

#44 Feature/input
  src/client/components/Input/Input.css
  src/client/components/Input/Input.js
  src/client/components/Input/Input.stories.js
Labels: storybook

#108 New created PR for tables Roles,user_roles and groups added -Group Pink
  src/server/migrations/20201125101025_create_roles_table.js
  src/server/migrations/20201129124000_create_user_roles_table.js
  src/server/migrations/20201129124100_create_groups_table.js
Labels: databases

#62 Storybook: Drop Down Field #18 added
  src/client/components/Dropdown/DropDown.css
  src/client/components/Dropdown/DropDown.js
  src/client/components/Dropdown/DropDown.stories.js
Labels: storybook

#123 API: Endpoint for retrieving the list of skills
  src/server/api/controllers/skills.controller.js
  src/server/api/routes/api-router.js
  src/server/api/routes/skills.router.js
Labels: backend

#119 Add 404page container
  src/client/components/footer/footer.styles.css
  src/client/containers/404Page/404Page.component.js
  src/client/containers/404Page/404Page.stories.js
  src/client/containers/404Page/404Page.styles.css
Labels: frontend

#118 change components styling
  src/client/components/HyfBigLogo/HyfBigLogo.style.css
  src/client/components/SignInButton/Button.css
  src/client/components/SignInButton/Button.js
Labels: frontend

#126 Migration/tables modification
  src/server/migrations/20201205214200_add_group_id_users_fk.js
  src/server/migrations/20201205214205_create_questions_topics_fk.js
  src/server/migrations/20201205214206_create_questions_events_fk.js
Labels: databases

#117 Modifying events
  src/server/migrations/20201202222630_modifying_maxParticipants_in_events.js
Labels: databases

#146 Adding seeds to all tables
  src/server/migrations/202012061600_modifying-mentor-id-in-mentor-skills-table.js
  src/server/seeds/development/01_groups.js
  src/server/seeds/development/02_organizations.js
  src/server/seeds/development/03_users.js
  src/server/seeds/development/04_modules.js
  src/server/seeds/development/05_events.js
  src/server/seeds/development/06_topics.js
  src/server/seeds/development/07_questions.js
  src/server/seeds/development/08_feedback.js
  src/server/seeds/development/09_roles.js
  src/server/seeds/development/10_user_roles.js
  src/server/seeds/development/11_skills.js
  src/server/seeds/development/12_mentors_skills.js
  src/server/seeds/development/13_events_users.js
  src/server/seeds/development/14_events_students.js
  src/server/seeds/development/15_events_mentors.js
  src/server/seeds/development/modules.js
Labels: backend

#156 API FIXED-skills: updated and working
  src/server/api/routes/api-router.js
  src/server/api/routes/skills.router.js
Labels: backend

#153 fix/api/topics
  src/server/api/controllers/topics.controller.js
Labels: backend

#152 Feature/footer profile photo
  src/client/components/footer/footer.js
  src/client/components/footer/profile.jpg
  src/client/components/footer/profile.png
  src/client/containers/ProfilePage/ProfilePage.component.js
  src/client/containers/ProfilePage/ProfilePage.stories.js
Labels: frontend

#112 API: Endpoint for retrieving the list of the current events/study groups
  src/server/api/controllers/events.controller.js
  src/server/api/routes/api-router.js
  src/server/api/routes/events.router.js
Labels: backend

#167 groups.controller fixed
  src/server/api/controllers/groups.controller.js
Labels: backend

#169 Added react-testify and an example Test button with onClick action
  package-lock.json
  package.json
  src/client/App.js
Labels: frontend

#163 access token from slack API
  package-lock.json
  package.json
  src/client/App.js
  src/client/containers/LoginPage/LoginPage.component.js
  src/client/containers/SlackAuthPage/SlackAuthPage.component.js
  src/server/api/controllers/slack_users.controller.js
  src/server/api/routes/api-router.js
  src/server/api/routes/slack.router.js
Labels: backend, frontend

#182 installed build-storybook for storybook deployement and added folder …
  .gitignore
  package.json
Labels: deployment

#180 Modal component style improvement
  src/client/components/Modal/Modal.css
Labels: frontend

#121 Components/events page
  src/client/App.js
  src/client/components/Appheader/AppHeader.style.css
  src/client/components/footer/footer.styles.css
  src/client/containers/EventsPage/EventsPage.component.js
  src/client/containers/EventsPage/EventsPage.js
  src/client/containers/EventsPage/EventsPage.styles.css
Labels: frontend

#166 AppHeader CSS improvement
  src/client/components/Appheader/AppHeader.style.css
Labels: frontend

#165 userContext issue done
  src/client/App.js
  src/client/context/UserContextTest.js
  src/client/context/userContext.js
Labels: frontend

#158 Registration Page - Student Registration Page
  src/client/App.js
  src/client/assets/images/hyf-logo.png
  src/client/components/Avatar/Avatar.css
  src/client/components/Avatar/Avatar.js
  src/client/components/Input/Input.css
  src/client/components/footer/profile.png
  src/client/containers/RegistrationPage/RegistrationPage.component.js
  src/client/containers/RegistrationPage/StudentRegistrationPage/StudentRegistrationPage.component.js
  src/client/containers/RegistrationPage/StudentRegistrationPage/StudentRegistrationPage.component.stories.js
  src/client/containers/RegistrationPage/StudentRegistrationPage/StudentRegistrationPage.styles.css
Labels: frontend

#170 API: Fix /api/modules
  src/server/api/controllers/modules.controller.js
  src/server/api/routes/modules.router.js
Labels: backend, bug

#172 change selection page and adjust RadioButton
  src/client/components/Radio/ButtonRadio.css
  src/client/components/Radio/ButtonRadio.js
  src/client/components/Radio/ButtonRadio.stories.js
  src/client/components/SelectionPage/HYF.logo.svg
  src/client/components/SelectionPage/SelectionPage.js
  src/client/components/SelectionPage/Selectionpage.css
  src/client/containers/SelectionPage/HYF.logo.svg
  src/client/containers/SelectionPage/SelectionPage.component.js
  src/client/containers/SelectionPage/Selectionpage.css
  src/client/containers/SelectionPage/Selectionpage.stories.js
Labels: frontend, storybook

#157 API: create an endpoint for fetching organizations #104
  src/server/api/controllers/organizations.controller.js
  src/server/api/routes/api-router.js
  src/server/api/routes/organizations.router.js
Labels: backend

#181 EventCardText improvement
  src/client/components/EventCardText/EventCardText.js
Labels: frontend

#160 Registration Page: Admin Registration Page
  src/client/App.js
  src/client/containers/RegistrationPage/AdminRegistrationPage/AdminRegistrationPage.component.js
  src/client/containers/RegistrationPage/AdminRegistrationPage/AdminRegistrationPage.stories.js
  src/client/containers/RegistrationPage/AdminRegistrationPage/AdminRegistrationPage.styles.css
Labels: frontend

#174 Modal View Cancelation/Deletion of Mentor's event registration
  src/client/components/ModalWithCancelRegistration/ModalWithCancelRegistration.css
  src/client/components/ModalWithCancelRegistration/ModalWithCancelRegistration.js
  src/client/components/ModalWithCancelRegistration/ModalWithCancelRegistration.stories.js
Labels: frontend

#161 Registration Page: Mentor Registration Page
  src/client/App.js
  src/client/containers/RegistrationPage/MentorRegistrationPage/MentorRegistrationPage.component.js
  src/client/containers/RegistrationPage/MentorRegistrationPage/MentorRegistrationPage.stories.js
  src/client/containers/RegistrationPage/MentorRegistrationPage/MentorRegistrationPage.styles.css
Labels: frontend

#189 Disabled button
  src/client/components/Button/Button.js
  src/client/components/Button/Button.stories.js
  src/client/components/Button/Button.styles.css
Labels: frontend

#173 Modal for cancel event is created
  src/client/components/ModalViewCancelEvent/ModalViewCancelEvent.js
  src/client/components/ModalViewCancelEvent/ModalViewCancelEvent.stories.js
Labels: frontend

#193 stylelint error
  package.json
Labels: fix

#159 modal view for feedback
  src/client/components/ModalWithFeedback/ModalWithFeedback.css
  src/client/components/ModalWithFeedback/ModalWithFeedback.js
  src/client/components/ModalWithFeedback/ModalWithFeedback.stories.js
Labels: frontend

#198 add moment package
  package-lock.json
  package.json
Labels: backend

#186 view modal for specific event
  src/client/containers/Admin-Event-details/Admin-Event-modal-view.js
  src/client/containers/Admin-Event-details/Admin-Modal-View.stories.js
  src/client/containers/Admin-Event-details/Admin-event-modal.style.css
  src/client/containers/Admin-Event-details/Elastic.logo.svg
  src/client/containers/Admin-Event-details/Zendesk.logo.svg
Labels: frontend

#196 Updating tables according to the latest DB_diagram
  src/server/migrations/20201216113500_ add_timezone_in_users.js
  src/server/migrations/20201216113600_add_organization_id_in_events.js
  src/server/migrations/20201216113700_add_group_id_in_events.js
  src/server/migrations/20201216123900_delete_events_mentors.js
  src/server/migrations/20201216124000_delete_events_students.js
  src/server/migrations/20201216124100_event_id_to_events_users_fk.js
  src/server/migrations/20201216124300_drop_comment_&-status_from_events_users.js
  src/server/migrations/20201216124400_drop_open_feedback_from_feedback.js
  src/server/migrations/20201216124500_drop_2_fk_columns_from_feedback.js
  src/server/migrations/20201216124600_add_event_id_into_feedback_fk.js
  src/server/migrations/20201216124700_add_description_to_questions.js
  src/server/seeds/development/05_events.js
  src/server/seeds/development/08_feedback.js
  src/server/seeds/development/13_events_users.js
  src/server/seeds/development/14_events_students.js
  src/server/seeds/development/15_events_mentors.js
Labels: databases

#191 Modal View to EDIT an event that is not past
  src/client/components/EditEventsModal/EditEventsModal.css
  src/client/components/EditEventsModal/EditEventsModal.js
  src/client/components/EditEventsModal/EditEventsModal.stories.js
Labels: frontend

#197 linkage in footer to profile page was added
  src/client/components/footer/footer.js
  src/client/containers/SignIn/index.js
  src/client/context/userContext.js
Labels: advanced, frontend

#201 API endpoint for the deletion of a specific event that is not past.
  src/server/api/controllers/events.controller.js
  src/server/api/routes/events.router.js
Labels: backend

#202 Add login-test page for quick login as a different user.
  .firebaserc
  firebase.json
  package-lock.json
  package.json
  src/client/App.js
  src/client/AppContainer.js
  src/client/components/Auth/AuthenticatedRoute.js
  src/client/components/Loader/index.js
  src/client/components/Navigation/Header.js
  src/client/containers/Home/Home.js
  src/client/containers/LoginTestPage/LoginTestPage.js
  src/client/containers/LoginTestPage/index.js
  src/client/containers/Profile/index.js
  src/client/containers/ResetPassword/index.js
  src/client/containers/SignIn/index.js
  src/client/containers/SignUp/index.js
  src/client/context/UserContextTest.js
  src/client/context/userContext.js
  src/client/index.js
  src/client/serviceWorker.js
  src/client/utils/fetchWithAuth.js
  src/server/api/auth/authMiddleware.js
  src/server/api/routes/api-router.js
  src/server/api/routes/self.router.js
  src/server/app.js
  src/server/config/db.js
  src/server/knexfile.js
  src/server/seeds/development/03_users.js
  src/server/seeds/development/09_roles.js
  src/server/seeds/development/10_user_roles.js
Labels: backend, frontend

#207 Authentication flow with Slack
  src/client/App.js
  src/client/components/Auth/AuthenticatedRoute.js
  src/client/containers/SlackAuthPage/SlackAuthPage.component.js
  src/client/containers/SlackAuthPage/SlackAuthPage.styles.css
  src/client/context/userContext.js
  src/client/index.css
  src/server/api/auth/authMiddleware.js
  src/server/api/controllers/slack_users.controller.js
  src/server/api/controllers/users.controller.js
  src/server/api/routes/self.router.js
  src/server/api/routes/slack.router.js
  src/server/app.js
Labels: backend, frontend

#190 Modal: Create Event
  src/client/components/DateTime/DateTime.js
  src/client/components/Modal/Modal.css
  src/client/containers/ModalCreateEvents/ModalCreateEvents.js
  src/client/containers/ModalCreateEvents/ModalCreateEvents.stories.js
  src/client/containers/ModalCreateEvents/ModalCreateEvents.styles.css
Labels: frontend

#211 fixing login page style
  src/client/components/HyfBigLogo/HyfBigLogo.style.css
  src/client/components/SignInButton/Button.css
  src/client/index.css
Labels: frontend

#168 API:endpoint to write the feedback for each event participation-student
  src/server/api/controllers/feedbacks.controller.js
  src/server/api/routes/api-router.js
  src/server/api/routes/feedbacks.router.js
Labels: backend

#222 Modal View Cancel Student's Registration
  src/client/components/ModalAdminCancelStudentRegistration/ModalAdminCancelStudentRegistration.js
  src/client/components/ModalAdminCancelStudentRegistration/ModalAdminCancelStudentRegistration.stories.js
  src/client/components/ModalAdminCancelStudentRegistration/modalAdminCancelStudentRegistration.css
Labels: frontend, storybook

#212 time zone component
  src/client/components/TimeZone/TimeZone.component.js
  src/client/components/TimeZone/TimeZone.stories.js
Labels: frontend

#223 footer link-Router
  src/client/components/footer/footer.stories.js
Labels: frontend, storybook

#232 Cancel registration of student from event
  src/server/api/controllers/events.controller.js
  src/server/api/routes/events.router.js
Labels: backend

#228 endpoint for registering mentor
  src/server/api/controllers/mentor.controller.js
  src/server/api/routes/api-router.js
  src/server/api/routes/mentor.router.js
Labels: backend

#230 Backend/users endpoint
  src/server/api/controllers/users.controller.js
  src/server/api/routes/api-router.js
  src/server/api/routes/users.router.js
Labels: backend

#214 Footer component improvement add link and css
  package-lock.json
  src/client/components/footer/footer.js
  src/client/components/footer/footer.styles.css
Labels: frontend

#239 Frontend: Logout route
  src/client/App.js
  src/client/components/Logout/Logout.js
Labels: frontend

#240 API: endpoints for creating, updating, and deleting skills
  src/server/api/controllers/skills.controller.js
  src/server/api/routes/skills.router.js
Labels: backend

#236 API: create, update, delete topics
  src/server/api/controllers/topics.controller.js
  src/server/api/routes/topics.router.js
Labels: backend, databases

#233 AppHeader CSS improvement
  src/client/components/Appheader/AppHeader.component.js
  src/client/components/Appheader/AppHeader.style.css
Labels: frontend

#229 Student registration page- data from backend using "/api/groups"
  src/client/components/Dropdown/DropDown.js
  src/client/containers/RegistrationPage/StudentRegistrationPage/StudentRegistrationPage.component.js
Labels: frontend

#227 API:created endpoint to register student
  src/server/api/controllers/user.controller.js
  src/server/api/routes/api-router.js
  src/server/api/routes/user.router.js
Labels: backend

#237 Endpoint to retrieve all future events for a user
  src/server/api/controllers/eventsUsers.controller.js
  src/server/api/routes/api-router.js
  src/server/api/routes/eventsUsers.router.js
Labels: backend

#209 implement Model View Registering For An Event
  .vscode/settings.json
  src/client/components/Dropdown/DropDown.css
  src/client/components/ModelViewRegisteringForAnEvent/HYF.logo.svg
  src/client/components/ModelViewRegisteringForAnEvent/ModelViewRegisteringForAnEvent.css
  src/client/components/ModelViewRegisteringForAnEvent/ModelViewRegisteringForAnEvent.js
  src/client/components/ModelViewRegisteringForAnEvent/ModelViewRegisteringForAnEvent.stories.js
Labels: frontend, storybook

#242 mentor registration cancelation
  src/server/api/controllers/events.users.controller.js
  src/server/api/routes/api-router.js
  src/server/api/routes/events.users.router.js
Labels: backend

#241 mentor registration page
  src/client/containers/RegistrationPage/MentorRegistrationPage/MentorRegistrationPage.component.js
Labels: frontend

#205 Endpoint to edit a future event by admin
  src/server/api/controllers/events.controller.js
  src/server/api/routes/api-router.js
  src/server/api/routes/events.router.js
  src/server/api/routes/user.router.js
Labels: backend

#245 Restyle selection page
  package-lock.json
  package.json
  src/client/components/Layout/Layout.js
  src/client/components/Layout/Layout.styles.css
  src/client/components/Layout/index.js
  src/client/components/ModelViewRegisteringForAnEvent/ModelViewRegisteringForAnEvent.css
  src/client/components/Radio/ButtonRadio.css
  src/client/components/Radio/ButtonRadio.js
  src/client/components/Radio/ButtonRadio.stories.js
  src/client/containers/SelectionPage/SelectionPage.component.js
  src/client/containers/SelectionPage/SelectionPage.styles.css
  src/client/containers/SelectionPage/Selectionpage.css
  src/client/containers/SelectionPage/Selectionpage.stories.js
  src/server/api/routes/api-router.js
Labels: frontend
