Repository HackYourFuture-CPH/web-dev-rooms, pull requests merged in 2020-11, with the labels that each got.

#52 add AppHeader component
  src/client/components/Appheader/AppHeader.component.js
  src/client/components/Appheader/AppHeader.stories.js
  src/client/components/Appheader/AppHeader.style.css
  src/client/components/Appheader/Vector.svg
Labels: storybook

#47 API: Endpoint for retrieving the list of groups #21
  src/server/api/controllers/groups.controller.js
  src/server/api/routes/api-router.js
  src/server/api/routes/groups.router.js
Labels: backend

#83 Add Route404 component
  src/client/App.js
  src/client/components/Route404/Route404.js
  src/client/components/Route404/index.js
Labels: frontend

#48 Storybook/heading
  src/client/components/Heading/Heading.js
  src/client/components/Heading/heading.stories.js
  src/client/components/Heading/heading.style.css
Labels: storybook

#54 adding Topics Endpoints in project
  src/server/api/controllers/topics.controller.js
  src/server/api/routes/api-router.js
  src/server/api/routes/topics.router.js
Labels: backend

#56 Storybook: HackYourFuture Logo(Big) + App Title
  src/client/components/HyfBigLogo/HyfBigLogo.js
  src/client/components/HyfBigLogo/HyfBigLogo.stories.js
  src/client/components/HyfBigLogo/HyfBigLogo.style.css
  src/client/components/HyfBigLogo/hyfLogo.png
Labels: storybook

#82 Dummy pages created
  src/client/App.js
  src/client/containers/404Page/404Page.component.js
  src/client/containers/EventsPage/EventsPage.component.js
  src/client/containers/LoginPage/LoginPage.component.js
  src/client/containers/ProfilePage/ProfilePage.component.js
  src/client/containers/RegistrationPage/RegistrationPage.component.js
  src/client/containers/SelectionPage/SelectionPage.component.js
Labels: backend, frontend

#85 Page footer
  src/client/components/footer/footer.js
  src/client/components/footer/footer.styles.css
Labels: frontend

#88 implement selection page
  src/client/components/SelectionPage/HYF.logo.svg
  src/client/components/SelectionPage/SelectionPage.js
  src/client/components/SelectionPage/Selectionpage.css
  src/client/components/SelectionPage/Selectionpage.stories.js
Labels: frontend

#45 Storybook: Modal View with Title and closing button X #19
  src/client/components/Modal/Modal.css
  src/client/components/Modal/Modal.js
  src/client/components/Modal/Modal.stories.js
Labels: storybook

#73 Migrations for skills, mentors_skills tables
  src/server/migrations/20201115193601_create_skills_table.js
  src/server/migrations/202011251936_create_skills_table.js
  src/server/migrations/202011252038_create_mentors_skills_table.js
  src/server/seeds/development/skills.js
Labels: databases
