Repository HackYourFuture-CPH/web-dev-rooms, pull requests merged in 2021-01, with the labels that each got.

#247 DropDowm Bug fixed
  src/client/components/Dropdown/DropDown.js
  src/client/components/Dropdown/DropDown.stories.js
  src/client/components/TimeZone/TimeZone.component.js
  src/client/components/TimeZone/TimeZone.stories.js
Labels: frontend, storybook

#246 Help Text Component
  src/client/components/HelpText/HelpText.css
  src/client/components/HelpText/HelpText.js
  src/client/components/HelpText/HelpText.stories.js
  src/client/containers/RegistrationPage/AdminRegistrationPage/AdminRegistrationPage.component.js
  src/client/containers/RegistrationPage/MentorRegistrationPage/MentorRegistrationPage.component.js
  src/client/containers/RegistrationPage/StudentRegistrationPage/StudentRegistrationPage.component.js
  src/client/containers/SelectionPage/SelectionPage.component.js
Labels: frontend, storybook

#154 API: Endpoint to retrieve all the registered and past events for a specific user
  src/server/api/controllers/user.controller.js
  src/server/api/routes/api-router.js
  src/server/api/routes/user.router.js
Labels: backend

#265 A new column 'admin_role' added to users table
  src/server/migrations/20210102234000_add_admin_role_to_users.js
Labels: databases

#271 Restyle registration pages
  src/client/components/Avatar/index.js
  src/client/containers/RegistrationPage/AdminRegistrationPage/AdminRegistrationPage.component.js
  src/client/containers/RegistrationPage/AdminRegistrationPage/AdminRegistrationPage.styles.css
  src/client/containers/RegistrationPage/MentorRegistrationPage/MentorRegistrationPage.component.js
  src/client/containers/RegistrationPage/MentorRegistrationPage/MentorRegistrationPage.styles.css
  src/client/containers/RegistrationPage/Registration.styles.css
  src/client/containers/RegistrationPage/StudentRegistrationPage/StudentRegistrationPage.component.js
  src/client/containers/RegistrationPage/StudentRegistrationPage/StudentRegistrationPage.styles.css
Labels: frontend

#234 Feature/student profile page
  src/client/App.js
  src/client/containers/ProfilePage/StudentProfile/StudentProfile/StudentProfile.component.js
  src/client/containers/ProfilePage/StudentProfile/StudentProfile/StudentProfile.stories.js
  src/client/containers/ProfilePage/StudentProfile/StudentProfile/StudentProfile.style.css
Labels: frontend

#277 Mentor Profile page
  src/client/App.js
  src/client/components/TimeZone/TimeZone.component.js
  src/client/components/TimeZone/TimeZone.stories.js
  src/client/containers/ProfilePage/MentorProfile/MentorProfile.component.js
  src/client/containers/ProfilePage/MentorProfile/MentorProfile.stories.js
  src/client/containers/ProfilePage/MentorProfile/MentorProfile.style.css
  src/client/containers/ProfilePage/ProfilePage.component.js
Labels: frontend

#278 Register admin
  src/client/containers/RegistrationPage/AdminRegistrationPage/AdminRegistrationPage.component.js
  src/client/containers/RegistrationPage/AdminRegistrationPage/AdminRegistrationPage.stories.js
  src/client/containers/RegistrationPage/StudentRegistrationPage/StudentRegistrationPage.component.js
  src/client/utils/formatApiError.js
  src/server/api/auth/requireAuthMiddleware.js
  src/server/api/controllers/user.controller.js
  src/server/api/routes/user.router.js
  src/server/app.js
Labels: backend, demo, frontend

#275 EventsPage
  src/client/components/CardWithEventsOrStudyGroups/CardWithEventsOrStudyGroups.styles.css
  src/client/containers/EventsPage/EventsPage.js
  src/client/containers/EventsPage/EventsPage.styles.css
  src/server/api/controllers/events.controller.js
Labels: demo, frontend

#273 App header with logout button
  src/client/components/Appheader/AppHeader.component.js
  src/client/components/Appheader/AppHeader.style.css
  src/client/components/Button/Button.js
  src/client/components/Button/Button.stories.js
  src/client/components/Button/Button.styles.css
Labels: demo, frontend

#274 Student home page is created
  src/client/App.js
  src/client/components/Card/Card.styles.css
  src/client/components/CardWithEventsOrStudyGroups/CardWithEventsOrStudyGroups.styles.css
  src/client/containers/EventsPage/EventsPage.js
  src/client/containers/Home/Home.js
  src/client/containers/ProfilePage/MentorProfile/MentorProfile.component.js
  src/client/containers/ProfilePage/StudentProfile/StudentProfile/StudentProfile.component.js
  src/client/containers/StudentHome/StudentHome.js
  src/client/containers/StudentHome/StudentHome.styles.css
  src/client/context/userContext.js
  src/server/api/controllers/events.controller.js
  src/server/api/controllers/eventsUsers.controller.js
  src/server/api/controllers/users.controller.js
  src/server/api/routes/eventsUsers.router.js
Labels: demo, frontend

#276 Api/get profile student
  src/server/api/controllers/profile.controller.js
  src/server/api/routes/api-router.js
  src/server/api/routes/profile.router.js
Labels: backend

#272 Created a skill page and added a route
  src/client/App.js
  src/client/containers/SkillsPage/SkillsPage.js
Labels: frontend

#280 Register/cancel button for the event issue #268
  src/client/components/CancelButtonWithEventsStudyGroups/CancelButtonWithEventsStudyGroups.css
  src/client/components/CancelButtonWithEventsStudyGroups/CancelButtonWithEventsStudyGroups.js
  src/client/components/CancelButtonWithEventsStudyGroups/CancelButtonWithEventsStudyGroups.stories.js
Labels: demo, frontend, storybook

#286 Create a page that will list all topics #261
  src/client/App.js
  src/client/containers/TopicsPage/TopicsPage.js
Labels: frontend

#287 Endpoint:admin profile is created
  src/client/App.js
  src/client/components/Input/Input.js
  src/client/components/Input/Input.stories.js
  src/client/components/footer/footer.js
  src/client/containers/ProfilePage/AdminProfile/AdminProfile.js
  src/client/containers/ProfilePage/AdminProfile/AdminProfile.styles.css
  src/server/api/controllers/profile.controller.js
  src/server/api/routes/profile.router.js
Labels: backend

#290 Detail endpoint
  src/server/api/controllers/eventDetail.controller.js
  src/server/api/routes/api-router.js
  src/server/api/routes/eventDetail.router.js
Labels: backend

#294 Student profile update added
  src/server/api/controllers/profile.controller.js
  src/server/api/routes/profile.router.js
Labels: backend

#306 Refactor student home
  src/client/AppContainer.js
  src/client/components/ErrorBoundary/ErrorBoundary.js
  src/client/components/ErrorBoundary/ErrorBoundary.styles.css
  src/client/components/ModalAdminCancelStudentRegistration/modalAdminCancelStudentRegistration.css
  src/client/components/ModalWithCancelRegistration/ModalWithCancelRegistration.css
  src/client/components/ModalWithCancelRegistration/ModalWithCancelRegistration.js
  src/client/components/footer/NavItem.js
  src/client/containers/StudentHome/NoRegisteredEvents.js
  src/client/containers/StudentHome/RegisteredEvent.js
  src/client/containers/StudentHome/StudentHome.js
  src/client/containers/StudentHome/getOrganizationLogoForEvent.js
  src/client/hooks/useQuery.js
  src/server/api/controllers/events.controller.js
  src/server/api/controllers/eventsUsers.controller.js
  src/server/api/controllers/helpers.js
  src/server/api/routes/api-router.js
  src/server/api/routes/events.router.js
  src/server/api/routes/eventsUsers.router.js
Labels: backend, frontend

#293 API: Update admin profile
  src/server/api/controllers/profile.controller.js
  src/server/api/routes/profile.router.js
Labels: backend
